---
- name: "Add bash include file for git"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /usr/local/etc/bash.d/{{ item }}
    mode: 0644
    owner: root
    group: root
  loop: "{{ ct_git_includes }}"
  become: true
  tags: [ct-git]

- name: "Install package"
  ansible.builtin.apt:
    name: "{{ ct_git_pkgs }}"
    state: "{{ ct_git_state }}"
  become: true
  tags: [ct-git]
...
